### ISSUE TITLE
[要望] データ印の設定

### ISSUE THREAD

**Issue by reiven0** [RelaxTools/RelaxTools-Addin#24]
いつも便利に使わせて頂いています。
下記要望ですが、ご検討頂けると幸いです。

・データ印の上/中/下段それぞれのFont種類、サイズを個別変更
・ '15.6.26 というように、先頭に" ' " アポロストロフィを書き込みたいが、'_15.6.26というように
　アポロストロフィと年の数字との間に、不自然な隙間が空いてしまうので、書式オプションに
　標準で " ' " を追加して欲しい。

**Comment by RelaxTools** [comment]
ご愛用ありがとうございます。
どんな文字またはどんなフォントだとうまくいかないなどありますか？
なるべく自動で手間なく作っているつもりですが、
全てのパターンでうまくいくように作るのは難しいです。

アポストロフィと空白ですが、フォントによりませんか？
固定フォントだとアポストロフィ自体が小さいので指摘のように見える場合があると思います。

**Comment by alucky555** [comment]
便利に使わせていただいております。感謝します。
さて、「データ印」を使用しようかと思い、設定し始めたのですが、データ印の上部・中央部・下部の下部の部分で英語（英語略称の企業名です）で入力すると、上部の漢字のように、左右は中央に配置されるのですが、上下はかなり上（中央部との仕切線にくっついて）に配置されてしまいます。下部部分に上下も中央に配置することは可能でしょうか。

**Comment by RelaxTools** [comment]
どんな感じですかね。。イメージがあると嬉しいです
![image](https://user-images.githubusercontent.com/10811735/49733392-a8c3e480-fcc4-11e8-971b-371a6bbb44fd.png)

**Comment by alucky555** [comment]
アッ！　まさしく、このとおりです。特に下段部分。上段は日本名なので、現状で問題ありません。
できれば、改良いただければ幸いです。とても助かります。

**Comment by RelaxTools** [comment]
alucky555 さんのＰＣでは日付の下のラインにくっついていると言っていますが、この画像ではくっついていません。フォントを変えてみてもくっつくほどではありません。
下もそれほど空きがあるわけではないですが、どうあるべきなのでしょうか？

**Comment by alucky555** [comment]
例示で示された押印画像の文字の表示を参考にして、改行の状況を確認しましたところ、文字の下部に改行が入っており、これが、文字を上部に押し上げていたことが判明しました。失礼しました。解決済となりましたので、お報せいたします。

**Comment by RelaxTools** [comment]
クローズします。
