### ISSUE TITLE
Excel 2007 クイックアクセスツールバーでエラー

### ISSUE THREAD

**Issue by Soog1459** [RelaxTools/RelaxTools-Addin#27]
Excel 2007 クイックアクセスツールバーを追加しようと
「コマンドの選択」を「すべてのコマンド」にすると
山のようにメッセージなしのエラーウィンドウが出ます。

![image](https://cloud.githubusercontent.com/assets/3417405/9750548/42eb8b34-56d4-11e5-8bea-c7d4254ff8c6.png)

--------------------------------------------------
RelaxTools AddIn Ver. 3.23.0 (VerticalClimbRoll)
Microsoft Windows 7 (64bit)
Microsoft Excel 2007 Build 6727 (32bit)

Scripting.FileSystemObject:OK
Shell.Application:OK
WScript.Shell:OK
VBScript.RegExp:OK
System.Collections.ArrayList:OK
System.Text.StringBuilder:OK
System.Text.UTF8Encoding:OK
System.Security.Cryptography.MD5CryptoServiceProvider:OK
System.Security.Cryptography.SHA1Managed:OK
System.Security.Cryptography.SHA256Managed:OK
System.Security.Cryptography.SHA384Managed:OK
System.Security.Cryptography.SHA512Managed:OK

**Comment by RelaxTools** [comment]
Excel 2007 の クイックアクセス ツールバーのカスタマイズ設定の際、コマンド選択で [すべてのコマンド] を選択すると空のエラー ダイアログ ボックスが表示される

Excel207のバグのようです。またパスワードのかかったExcelを開く際に、クイックアクセスツールバーにRelaxToolsの機能を登録している場合にも同様の現象になる場合があるようです。
対策はありません。
マイクロソフトサポートページへ
http://support.microsoft.com/kb/950530/ja
