### ISSUE TITLE
検索結果を選択しようとすると例外が発生する場合があります。

### ISSUE THREAD

**Issue by uyutanian** [RelaxTools/RelaxTools-Addin#31]
RelaxTools > 検索/置換 > セル・シェイプの正規表現検索／置換
を使用し、検索結果のセルにフォーカス仕様と結果リストの内の一つを選択すると
「アプリケーション定義またはオブジェクト定義のエラーです。」
とのダイアログが立ち上がる場合があります。

発生位置
frmSearchEx line 920 （sub lstResult_Change） 
```vb
Application.GoTo setCellPos(r(0)), True
```

発生内容
r(0) = <アプリケーション定義またはオブジェクト定義のエラーです。>

再現性に影響があるか不明ですが、
直前のIF文ではこちらを通っています。
```vb
Set r = Range("'[" & lstResult.List(lngCnt, C_SEARCH_BOOK) & "]" & lstResult.List(lngCnt, C_SEARCH_SHEET) & "'!" & lstResult.List(lngCnt, C_SEARCH_ID))
```

環境
Microsoft Excel 2010 14.0.7166.5000 (32bit)
RelaxTools AddIn Ver. 4.1.1 (RustRemover)

**Comment by RelaxTools** [comment]
自分も１回現象確認しています。現象までは特定できていません、少々お待ちください。

**Comment by RelaxTools** [comment]
4.1.2 で修正しました。
