### ISSUE TITLE
ツリー作成機能で、Excelのシートまでツリー表示して欲しい

### ISSUE THREAD

**Issue by JDG00000** [RelaxTools/RelaxTools-Addin#33]
切実にぜひ実現してほしいです。

**Comment by RelaxTools** [comment]
ちょっと現在、デスマーチ状態ですので年内は難しいかもしれません。

**Comment by JDG00000** [comment]
ご回答ありがとうございます。
こんなに早くご回答頂けると思わなかったので感激しました。
この機能が実現すれば、預った資料の一覧作成などがサクサクになると思います。
余裕が出来ましたらぜひともご検討をお願いします。

**Comment by RelaxTools** [comment]
4.7.0 で入れてみました。ブックを開くので遅くなりますがが。。

**Comment by JDG00000** [comment]
早々にご対応頂きありがとうございました。
思った通りにExcelのシート名が表示されました。
これで、面倒な資料作りが楽になります。感謝です。
最強のツリー表示機能になったと思います。

ＸＰ時代に「StructureT-Maker」というフリーソフトで出来ていたのですが、
以降のOSに対応しておらず、困っているユーザーが自分以外にもいると思います。
「フォルダ、Excelシート、ツリー表示機能」などで検索ヒットするようになると、ユーザーが増えるのではないかと思います。

要望をかなえて頂き、ありがとうございました。

**Comment by RelaxTools** [comment]
「StructureT-Maker」知りませんでした。喜んでいただいて何よりです。

**Comment by JDG00000** [comment]
先日はありがとうございました。
ここに書くべきことではないかもしれないのですが、「フォルダツリー取得機能」で、
「ハイパーリンク」の設定で「フォルダ」にチェックすると、指定したフォルダ内の１つ目のサブフォルダのところで処理が止まってしまいます。
これは、「Excelの中のシートを表示する」をチェックしてもしなくても同じでした。
指定したフォルダの直下には、ファイルやフォルダが混在する状態です。

どうぞよろしくお願いします。

**Comment by RelaxTools** [comment]
報告ありがとうございます。4.7.2で対応しました。また、コミットメッセージでissueを閉じるのやってみたかったのでやってみました。失礼！

**Comment by JDG00000** [comment]
あまりの対応の速さに唖然呆然、凄げー、すげーと感動しておりました。
ツリー、完璧っす！
ありがとうございました。

**Comment by JDG00000** [comment]
2016年に「フォルダツリー作成」をお願いした者です。
今でもこの機能を含めRelaxToolsの力を借りてお仕事しており、感謝しております。
遅れ馳せながらカンパさせて頂きました。
そのうち、そのうちと思いながら５年以上経ってしまいました。。。
今後もどうぞお体に気をつけてユーザーの力になって下さい。
ありがとう、ありがとう、ありがとう！
