### ISSUE TITLE
フォルダツリー作成がネットワークドライブでできない

### ISSUE THREAD

**Issue by koji072** [RelaxTools/RelaxTools-Addin#34]
複数のフォルダ、階層のフォルダツリーの作成ができません
途中で終了するように見えます

**Comment by koji072** [comment]
エクセル2010を使用してます
他のバージョンでは発生しないのでしょうか

**Comment by RelaxTools** [comment]
自宅で試してみたら動作しました。#33 のバグのせいかな？明日職場でも動作確認してみます。
動作確認は、Excel 2016 64bit版です。

**Comment by koji072** [comment]
ご対応ありがとうございます。
本日確認したら修正されていました。
動作確認は、Excel 2010 32bit版です
#33でも報告されているようにデグレっていたんでしょうか
これからも愛用させていただきます

**Comment by RelaxTools** [comment]
4.8.0でソートされない問題を修正しました。
