### ISSUE TITLE
検索機能に特定の書式を含む文字列を検索したい

### ISSUE THREAD

**Issue by koji072** [RelaxTools/RelaxTools-Addin#35]
いつも便利に使わせていただいています
先日はバグ対応ありがとうございました

セルの中に取り消し線や太字等の書式を含む文字列を検索する機能を追加していただけないでしょうか
よろしくお願いいたします

**Comment by RelaxTools** [comment]
セル書式の検索はExcel標準でもできますがアレじゃだめ？

**Comment by koji072** [comment]
Excel標準の検索機能だと書式を含むの検索ができませんでした
やり方が悪かったのかな・・
Excel標準だと置換ができないので希望しました
