### ISSUE TITLE
シートのマージ

### ISSUE THREAD

**Issue by koji072** [RelaxTools/RelaxTools-Addin#36]
本来であれば共有で出来ている機能なのですが、ファイルのサイズが大きくなると動作が異様に重くなる、複数人で作業をしていると保存タイミングによっては、ファイルが壊れる等々あり、共有機能が使えない状態です。
マージ元と先のシートを比較して、マージ元に入力された値のみをマージ先に反映できないでしょうか？
マージ先に別の値が入っていたら色付けする機能があると尚いいと思います
VLOOKUPでもできるのですが、シートが変わるたびにするのは手間がかかります
ご検討お願いいたします

**Comment by RelaxTools** [comment]
共有が失敗する環境ということで、あまりニーズがないと思います。
ごめんなさい。
