### ISSUE TITLE
リボンを非表示にするとアクセスキーが変化する(たび)

### ISSUE THREAD

**Issue by RelaxTools** [RelaxTools/RelaxTools-Addin#39]
タイトルの通り。
アクセスキーを固定にすれば対応可能だが、振るのは手間がかかる。

**Comment by tonierlu** [comment]
TortoiseSVN、TortoiseGit のリボンを非表示させたいのですが、できますでしょうか？

**Comment by RelaxTools** [comment]
対処法はここにあります
http://software.opensquare.net/relaxtools/support-2/firststep/

**Comment by tonierlu** [comment]
早々にご回答頂きまして、ありがとうございました。
