### ISSUE TITLE
付箋の管理画面について

### ISSUE THREAD

**Issue by crossn** [RelaxTools/RelaxTools-Addin#41]
RelaxTools-Addinをご提供くださり、感謝致します！
RelaxTools-Addinの存在を知り、これから活用させていただこうと考えておる者です。

付箋の機能をレビューなどに活用できると考えておりますが、当機能に対する要望がございます。
利用しているバージョンは、Ver.4.11.1 となります。

■変更依頼内容
内容の詳細が表示される部分のテキストボックス(txtPreview)が
MultiLine＝Falseの設定になっているため、改行がされません。
ここを改行がある場合に内容がそのまま表示されるようにTrueに変更して頂けないでしょうか。

また、これの設定変更と同時に、ScrollBarsの設定をfmScrollBarsBothに、
WordWrapの設定をFalseに設定して頂き、付箋の内容がそのまま表示されるようにして頂けると大変便利です。

対応につきまして、ご検討くださいますようお願い致します。

**Comment by RelaxTools** [comment]
すみません、だいぶ前に対応済みでした。
