### ISSUE TITLE
SVNロックの取得について

### ISSUE THREAD

**Issue by house1059** [RelaxTools/RelaxTools-Addin#43]
RelaxToolsのご提供ありがとうございます。いつも活用させていただいています。
■使用環境について
RelaxTools AddIn Ver. 4.13.10 (RustRemover)
Microsoft Windows 7 (64bit)
Microsoft Excel 2010 Build 7183 (32bit)

TortoiseSVNでExcelを管理しており、常にロックをかける運用となっております。
その環境でExcel側からRelaxToolsを通してロック取得を行った場合、現在開いているExcelのPathではなく
\user\Documents\の直下に新たにファイルをコピーしているようです。
そのため、コミットしようとしたときに「バージョン管理外のブックです」と表示されてしまいます。

**Comment by RelaxTools** [comment]
自分のローカルでやってみたのですが再現しないですね。
以前の職場でもロックは普通に出来ていました。


![image](https://user-images.githubusercontent.com/10811735/30324594-91c4ba62-97fc-11e7-8119-5e3f3cef64bf.png)

![image](https://user-images.githubusercontent.com/10811735/30324609-9c6c914c-97fc-11e7-8c2f-a8d121b6875d.png)

![image](https://user-images.githubusercontent.com/10811735/30324620-aa6ad4ca-97fc-11e7-9624-1b01ba95d39b.png)

![image](https://user-images.githubusercontent.com/10811735/30324635-b762ad06-97fc-11e7-8047-fdb76f71d294.png)

\user\Documents\ 直下というのはSVNのHOMEと思われるのでなにか確かにあるっぽい感じはしますが。
SVNのなにか設定なのかな。。。。

![image](https://user-images.githubusercontent.com/10811735/30324743-07168bb0-97fd-11e7-9b41-e33a5900d685.png)

**Comment by house1059** [comment]
ご確認ありがとうございます。
再現する条件を調べてみたところ、ファイルの属性が「読み取り専用」になっておりました。
svnのプロパティにneeds-lockが付与されている場合、読み取り専用の属性が付き、その状態でRelax-Toolsからロック取得を行った場合、「ブックが変更されています。保存しますか？」と問い合わせがあり、読み取り専用なので\user\Documet\に保存される現象のようです。

**Comment by RelaxTools** [comment]
なんとなくわかりました。
1.開いたときには読み取り専用属性なので、Excelは読み取り専用になっている。
2.ロックを取得するとローカルのファイルの読み取り専用が解除されるが、Excel自体は開きっぱなしなので読み取り専用のまま。
3.コミット時に読み取り専用なので上書き保存ができない。

なので、２のロック取得時にExcelファイルを開きなおす処理を追加したいと思います。

**Comment by house1059** [comment]
ご確認、ご対応ありがとうございます。
これからも是非使用させていただきます

**Comment by RelaxTools** [comment]
4.14.3 で対応しました

**Comment by house1059** [comment]
ご対応ありがとうございます。
確認環境が手元に無くなってしまいましたので、週明けから使用させていただきます。
