### ISSUE TITLE
十字カーソルを表示するとカーソルキーで移動できない

### ISSUE THREAD

**Issue by tomotomoexcel** [RelaxTools/RelaxTools-Addin#49]
いつもRelax-Toolsを愛用させて頂いています。
Relax-Tools Version 4.22.3において十字カーソルを表示するとカーソルキーで移動
できない模様です
一度、マウスクリック等でセルを選択しなおすとカーソルキーで移動できるように
なりますが可能であれば十字カーソルを表示開始した時点からカーソルキーで
移動できようにしてもらえるとありがたいです。
よろしくご検討のほど、お願いします。

**Comment by RelaxTools** [comment]
4.23.0 で修正しました。

**Comment by tomotomoexcel** [comment]
早速のご対応、誠にありがとうございます。

2018年9月24日(月) 11:54 Yasuhiro Watanabe <notifications@github.com>:
