### ISSUE TITLE
図形を選択した状態で「RelasTools-メモ帳のボタン」を押すと、実行エラー53が出る。

### ISSUE THREAD

**Issue by taka1985** [RelaxTools/RelaxTools-Addin#61]
https://github.com/RelaxTools/RelaxTools-Addin/blob/87859bb4f10e3164122871e9dabc92fb51f777c5/Source/src/Modules/basMacro.bas#L2814

通常はあり得ないですが、
図形を選択した状態で、セルを外部アプリで編集するボタンを押すと、エラーになります。
![image](https://user-images.githubusercontent.com/4952193/84093516-6902c800-aa35-11ea-9ac6-f1051aa6aa15.png)
↓
![image](https://user-images.githubusercontent.com/4952193/84093526-728c3000-aa35-11ea-887d-334f90b6431d.png)

理由は、外部編集中の中間ファイルが未生成なのにKillコマンドが動作するため。

**Comment by taka1985** [comment]
Sub cellEditExt()

```
e:
    On Error Resume Next
    Close
    
    Set FS = Nothing
    Set utf8 = Nothing
    
@@    If strFileName <> "" Then
        Kill strFileName
@@    End If
    
    Unload frmInformation
    
End Sub
```
@@の部分を追加すればOKです。

**Comment by RelaxTools** [comment]
いつかわすれましたが、図形を選択していた時にはエディタ編集を起動できないようにしました。
