### ISSUE TITLE
A1C1のトグルボタン反映の仕組

### ISSUE THREAD

**Issue by takanaweb5** [RelaxTools/RelaxTools-Addin#64]
技術的なことで教えて頂きたいです。

当方リボンを使ってEXCELアドインを開発しているものですがEXCELのある状態を、リボン上のチェックボックスに反映する仕組みを検討しています。
当然チェックボックスをチェックした時にはイベントが発生して状態を捕捉することが可能ですが、
以外の方法で状態を変更された場合のイベントを捕捉する仕組みに困っています。
１つの方法として、CommandBarsのOnUpdateイベントを使用することも考えましたが、予期せぬ副作用が心配で思案中です。

そこでRelaxToolsを参考にさせて頂こうと使用してみたところ、A1C1参照形式のトグルボタンが
EXCELのオプションの[数式]のR1C1参照形式を使用するのチェックボックスで変更しても、反映されるように出来ています。
その仕組みをご教授頂けないでしょうか？
当方で調べたところ、RelaxToolsのタブ上のいずこかにマウスカーソルを遷移させただけで、a1Pressedイベントが発生しているようですが
いかなる仕組みによるものなのでしょうか？

以上突然のお願いですが、よろしくご教授願います。

**Comment by RelaxTools** [comment]
リボンを使っているなら
CustomUI.xml の getPressed あたりの記述を見てください。
            <toggleButton id="toggleReferenceStyle" image="r1c1"         getSupertip="RelaxTools.xlam!getSupertip" getDescription="RelaxTools.xlam!getDescription" getPressed="RelaxTools.xlam!a1Pressed" onAction="RelaxTools.xlam!a1OnAction"/>

**Comment by takanaweb5** [comment]
アドバイスありがとうございます。
参考にさせていただきます。

返事が遅れて大変申し訳ありませんでした。
