### ISSUE TITLE
Excelスクショモードで2枚貼付けされる

### ISSUE THREAD

**Issue by tabibi-BB** [RelaxTools/RelaxTools-Addin#67]
ExcelスクショモードをonにしてWin+Shift+Sで範囲指定のスクショをすると、同じ画像が間隔を開けて2枚貼付けされます。
また、確認してみたのですがExcelスクショモードをonでプリントスクリーンボタンでスクショすると貼付けされないです。(こちらは私使わないですが)
使用しているExcelのバージョンはOffice 365です。

**Comment by RelaxTools** [comment]
現象確認。RelaxTools のスクショモードでは、クリップボードを監視ししており、
クリップボードが更新されると画像を張り付けますが、Win + Shift + S でコピーした場合、
２回更新のメッセージが飛んでくるようです。対処方法は考えないとダメですね。
続けてメッセージが飛んでくる場合、２回目を無視するとか、画像が変わっていなかったら
張り付けないとか。すぐには対応できないです。

なお、PrtSc ボタンが動作しないのは再現しません。スクショ中のExcel 自身のスクショは無視しているので
そのせいでしょうか？

**Comment by tabibi-BB** [comment]
すぐの対応は出来ないこと理解しました、ご確認いただきましてありがとうございます。

PrtSc ボタンの動作はご指摘の通りでした、失礼しました。

**Comment by RelaxTools** [comment]
500msの待ち時間を入れたら、意外と安定してしまったのでリリースしました。
確認してみてください。

**Comment by tabibi-BB** [comment]
確認しました、貼付けされる画像が1枚になりました。
ありがとうございます！
