### ISSUE TITLE
ファイル名に「＃」があるとハイパーリンクが動作しない

### ISSUE THREAD

**Issue by RelaxTools** [RelaxTools/RelaxTools-Addin#72]
風柳
@furyutei

RelaxTools-Addin の「RelaxApps ＞ フォルダツリー作成」が便利だなと思って試していたら、「#」を含むファイル／フォルダへのリンクは「指定されたファイルを開くことができません。」になってしまいますね…。
※MS365 Excel(32ビット)＋RelaxTools AddIn Ver. 4.27.2 で確認

**Comment by RelaxTools** [comment]
フォルダツリー作成、Grepなどで起こりうるが、対処が難しい

https://support.microsoft.com/ja-jp/topic/office-%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0%E3%81%A7-%E3%83%8F%E3%82%A4%E3%83%91%E3%83%BC%E3%83%AA%E3%83%B3%E3%82%AF%E3%81%AE%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E5%90%8D%E3%81%AB%E3%82%B7%E3%83%A3%E3%83%BC%E3%83%97%E6%96%87%E5%AD%97%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%A7%E3%81%8D%E3%81%AA%E3%81%84-3dc41767-a82e-fc9b-c405-de8b1166be92

**Comment by furyutei** [comment]
一応、Hyperlinks.Add で Address を指定するときに「file:///」を付加＆「#」を「%23」に置き換えるという方法を見つけております（[→参考](https://gist.github.com/furyutei/4914ef96dd6cb5d12178fabcdc10d3ac/e262b6524795d826e6f71b8b0c0ec34ea488e642#file-knock026-vba-L61-L68)）。
詳しく検証したわけではないので、副作用があるのかもしれませんが……。

**Comment by RelaxTools** [comment]
風柳さん
　情報ありがとうございます。大丈夫そうなので、4.27.3リリースしました。

**Comment by furyutei** [comment]
4.27.3にて、[ご報告したとき](https://twitter.com/furyutei/status/1366237287596498945)と同じフォルダで確認しましたところ、フォルダ／ファイル名に「#」が含まれているものでも問題なく開くことができました。
ご対応ありがとうございました。
