### ISSUE TITLE
OneDrive上のファイルをTimeLeap機能を有効状態で保存した場合、「ファイルが見つかりません。」ダイアログが表示

### ISSUE THREAD

**Issue by taky-jp** [RelaxTools/RelaxTools-Addin#75]
OneDriveやSharePointOnline上のファイルをTimeLeap機能を有効状態で保存した場合、「ファイルが見つかりません。」ダイアログが表示されます。
OneDriveやSharePointOnline上のファイルの保存に成功しておりますが、TimeLeap機能側のバックアップファイルが作成されていません。
TimeLeap機能側のバックアップファイルの作成時にエラーが発生し、「ファイルが見つかりません。」ダイアログが表示されていると思われます。

ご確認のほどよろしくお願いします。

**Comment by RelaxTools** [comment]
OneDrive/SharePoint 対象のファイルは TimeLeap の対象外としました。＞4.27.5
エラーメッセージが出ないようになります。
対応しない理由は、OneDrive/Sharepoint で履歴管理ができるので不要と考えています。
よろしくお願いいたします。

**Comment by taky-jp** [comment]
ご返信が遅くなり申し訳ありません。
ご対応頂きありがとうございます。
