### ISSUE TITLE
English version available?

### ISSUE THREAD

**Issue by GerdBlomb** [RelaxTools/RelaxTools-Addin#82]
Is there an international version available? English maybe?

Thank you!

**Comment by jimbrig** [comment]
@RelaxTools Any English Versions?

**Comment by RelaxTools** [comment]
Dear valued customers,

We regret to inform you that we are unable to provide an English version of RelaxTools at this time. We understand that this may cause inconvenience and frustration, and we apologize for any disappointment this may cause.

Please know that we have explored all possible options to create an English version of our product, but unfortunately, it is not feasible for us at this time. We hope that you can understand our situation.

We appreciate your business and want to assure you that we remain committed to providing the best possible service and products to our customers. If you have any questions or concerns, please don't hesitate to contact us.

Thank you for your understanding.

Sincerely,

Yasuhiro Watanabe
