### ISSUE TITLE
2つの範囲の入れ替えについて

### ISSUE THREAD

**Issue by overdozer1124** [RelaxTools/RelaxTools-Addin#83]
編集⇒2つの範囲の入れ替え
の機能をとても活用させて頂いております。
しかしながら、セルの内容だけを入れ替えたい時に、罫線等の書式が一緒に移動してしまい
様式自体の書式が崩れるということが度々起こります。
出来れば書式を伴った移動の可不可を選択できるようにして頂けると幸いです。
是非ご検討の程よろしくお願い致します。

**Comment by RelaxTools** [comment]
4.28.0で対応しましたのでご確認ください。
