### ISSUE TITLE
「目次の作成」でページ番号がずれていってしまう

### ISSUE THREAD

**Issue by hiro-gj** [RelaxTools/RelaxTools-Addin#84]
「目次の作成」でページ番号がずれていってしまうのは既知の不具合でしょうか？
・RelaxTools-Addin-4.27.5
・Excel 2013

~~※取得期限：1週間~~
~~RelaxTools-Addin-4.27.5_「目次の作成」でページ番号がずれてしまう.mp4~~

**Comment by hiro-gj** [comment]
修正に向けて「VBAid」さんともコンタクト取ってみようと思います。

**Comment by hiro-gj** [comment]
どこからページ数がずれ始めるのかな？とみていましたら、
途中で「2回目の段落番号」のみがあるシートはページ数として加算できないのでしょうか？

[RTA4.27.5_「目次の作成」_途中で「2回目の段落番号」のみがあるシートはページ数として加算できない？(この図の場合9～10ページでずれている).png](https://nextcloud.graspheresupport.com/2021/index.php/s/BHSzka3Nj7Ecpo8)

**Comment by hiro-gj** [comment]
もし現在の「目次の作成」の仕様を修正されるとしたらこんな感じでしょうか？
・「シート」には、必ず１つは、段落番号が設定されていることが前提。
・「シート」内で「改ページ」しており、かつ新たな段落番号が無い場合は、先の段落番号のページに改ページ分を加算していただく。
・「シート」内の「改ページ」に「新たな段落番号」がある場合は、その段落番号から新たなページとして設定する。

**Comment by hiro-gj** [comment]
ただいまVBAidさんに相談開始しまして再現を確認頂きました。
（以下VBAidさんからのコメント抜粋）
> 不具合確認出来ました。
> 私の方で試した際は、シート内の中間に段落番号のないページを作って試していたため不具合が起きなかった様です。
> 段落番号の無いページをシートの最後に移したところ、-中略- ページがずれて目次が作成されました。

**Comment by RelaxTools** [comment]
調査ありがとうございます。
ソース確認してみます。
