### ISSUE TITLE
Window11 上の Excel2007 でも利用したい

### ISSUE THREAD

**Issue by JDG00000** [RelaxTools/RelaxTools-Addin#88]
これまでやむを得ない事情により、、Windows10上のExcel2007で、2007対応の最終版である Ver. 4.13.10 を利用しておりました。
Windows11上でも、同様に利用しようとしたところ、アドインの設定時にエラーとなってしまいます。

ﾌｧｲﾙ 'C:\Users\tanaka\AppData\Roaming\Microsoft\AddIns\Relaxtools.xlam' にｱｸｾｽできません。次のいずれかの理由が考えられます。
・ﾌｧｲﾙ名またはﾊﾟｽが存在しません。
・ﾌｧｲﾙが他のﾌﾟﾛｸﾞﾗﾑによって使用されています。
・保存しようとしているﾌﾞｯｸと同じ名前のﾌﾞｯｸが現在開かれています。

サポート対象外であることは重々承知なのですが、何とかこのエラーを回避できないものか、、という相談です。
ご対応頂けると大変ありがたいです。
どうぞよろしくお願いいたします。
![WS000002](https://user-images.githubusercontent.com/23372987/211446051-27ebd172-da57-428f-a27e-7b2db6ffcd0e.JPG)

**Comment by RelaxTools** [comment]
申し訳ないのですが、環境が作成できませんので対応は難しいです。
